# Ne pas modifier le format des deux lignes ci-dessous car elles sont utilisées dans le script postinstall
server.port: 8443
certificate-file: /usr/local/etc/iris/certificat/##MYHOSTNAME##.jks


server:
  ssl:
    key-store: ${certificate-file}
    key-store-password: ev8ahfae7EeTah3yohqu
    key-store-type: JKS
    
logging:
  level:
    com:
      afp:
        iris:
          sr:
            wm: info

cas.server-url-prefix: ${app.cas.baseUri}
cas.server-login-url: ${app.cas.baseUri}/login
cas.client-host-url: ${app.baseUri} # mettre la vip
cas.validation-type: CAS
cas.proxy-callback-url: https://##MYHOSTNAME##:${server.port}/casCallback # mettre le hostname spécifique du noeud
cas.proxy-receptor-url: /casCallback
cas.redirect-after-validation: false
cas.authentication-url-patterns: /login #url d'auth srwm

app:
  baseUri: "https://iris-wsm-pp.afp.com"
  documentsEndpoint: "${app.baseUri}/documents/"
  srwmComponentsEndpoint: "${app.baseUri}/components/"
  srwmCookie:
    isSecure: true # true requires https communication end to end from client to server
    domain: "iris-wsm-pp.afp.com"
    path: "/"


  cms:
    baseUri: "http://spar-cms-pp-cli-vip.afp.com/nuxeo/site"
    userinfoEndpoint: "${app.cms.baseUri}/userinfo"
    documentsEndpoint: "${app.cms.baseUri}/documents"
    storiesEndpoint: "${app.cms.baseUri}/stories/"
    documentValidateEndpointTemplate: "${app.cms.baseUri}/documents/{did}/validator"
    documentEditorEndpointTemplate: "${app.cms.baseUri}/documents/{did}/editor"
    phoenixEndpoint: "${app.cms.baseUri}/documents/phoenix"
  scom:
    baseUri: "http://anycast-iris-pp-sco-http.afp.com"
    componentsEndpoint: "${app.scom.baseUri}/components/"
    renditionsEndpoint: "${app.scom.baseUri}/components/renditions/"
    componentsEndpointById: "${app.scom.baseUri}/components/{id}"
    thumbnail:
      height: 320
      width: 320
      type: BIGFIT
  cas:
    baseUri: "https://spar-iris-pp-cas-https-cli-vip.afp.com/cas"

